AWSTemplateFormatVersion : "2010-09-09"
Description: EC2 instance with ssh and access to s3
Parameters:
    MyKeyPairName:
        Type: String
        Default: ash-go2
        Description: Enter a key pair name
Resources:
    RootRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument: #required
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                  - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: root #or AuthenticatedS3GetObjects
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: '*' #or s3:*
                  Resource: '*'
    RootInstanceProfile:
      Type: 'AWS::IAM::InstanceProfile'
      Properties:
        Path: /
        Roles:
          - !Ref RootRole
    MyInstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Allowing SSH from everywhere
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22 #Integer
            ToPort: 22 #Integer
            CidrIp: 0.0.0.0/0
    EC2Instance:
      Type: 'AWS::EC2::Instance'
      Properties:
        KeyName: !Ref MyKeyPairName
        ImageId: ami-0c94855ba95c71c99
        InstanceType: t2.micro
        IamInstanceProfile: !Ref RootInstanceProfile
        Monitoring: true
        SecurityGroupIds:
          - !GetAtt
            - MyInstanceSecurityGroup
            - GroupId
        UserData:
          Fn::Base64: |
             #!/bin/bash
             sudo su
             yum update -y
             aws s3 cp s3://aws-andy-test-001/the_file.txt '/home/ec2-user/the_file.txt'
